export const RECIPE_RESULTS_REQUEST = 'RECIPE_RESULTS_REQUEST';
export const RECIPE_RESULTS_SUCCESS = 'RECIPE_RESULTS_SUCCESS';
export const RECIPE_RESULTS_FAILURE = 'RECIPE_RESULTS_FAILURE';

export const RECIPE_PAGE_CHANGE_REQUEST = 'RECIPE_PAGE_CHANGE_REQUEST';
export const RECIPE_PAGE_CHANGE_SUCCESS = 'RECIPE_PAGE_CHANGE_SUCCESS';

export const RESULTS = 'results';
export const PAGE = 'page';
